routes/admin.php
<?php

Route::group(['as' => 'panel.', 'prefix' => 'panel', 'middleware' => ['web', 'role:admin'], 'namespace' => '\Admin'], function()
{
    Route::get('/', 'PanelController@index');
    Route::resource('listings', 'ListingsController');
	Route::get('/listings/{listing}/duplicate', 'ListingsController@duplicate')->name('listings.duplicate');
    Route::resource('categories', 'CategoriesController');
    Route::resource('users', 'UsersController');
	Route::resource('roles', 'RolesController');
    Route::resource('pages', 'PagesController');
    Route::resource('menu', 'MenuController');
    Route::any('/settings/remove', 'SettingsController@remove')->name('settings.remove');
    Route::resource('payments', 'PaymentsController');
    Route::resource('settings', 'SettingsController');
    Route::resource('orders', 'OrdersController');
    Route::resource('home', 'HomeController');
    Route::resource('addons', 'AddonsController');
    Route::get('/addon/{id}/toggle', 'AddonsController@toggle');
    Route::resource('themes', 'ThemesController');
    Route::get('/theme/{id}/toggle', 'ThemesController@toggle');
    Route::resource('pricing-models', 'PricingModelsController');
    Route::resource('fields', 'FieldsController');

});

Route::group(['as' => 'panel.', 'prefix' => 'panel', 'middleware' => ['web', 'role:admin|moderator'], 'namespace' => '\Admin'], function()
{
    Route::get('/', 'PanelController@index');
    Route::resource('users', 'UsersController');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('/test', function () {
    return view('welcome');
});
*/



include "admin.php";
include "payments.php";

Route::get('/cp', function () {
    if(env('DEMO_PANEL')) {
        \Auth::loginUsingId(1, true);
        return redirect("/panel");
    }
});

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => 'jailBanned'], function()
{
	Auth::routes();
    Route::get('email-verification', 'Auth\EmailVerificationController@sendEmailVerification')->name('email-verification.send');
    Route::get('email-verification/error', 'Auth\EmailVerificationController@getVerificationError')->name('email-verification.error');
    Route::get('email-verification/check/{token}', 'Auth\EmailVerificationController@getVerification')->name('email-verification.check');

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/browse', 'BrowseController@listings')->name('browse');
    Route::get('/categories', 'BrowseController@categories')->name('categories');

    Route::get('/pages/{slug?}', 'PageController@index')->name('page');
	Route::get('/contact', 'ContactController@index')->name('contact');
	Route::post('/contact', 'ContactController@postIndex')->name('contact.post');

	Route::get('/profile/{user}', 'ProfileController@index')->name('profile'); //PROFILE
	Route::get('/profile/{user}/follow', 'ProfileController@follow')->name('profile.follow'); //PROFILE

	//LISTINGS
	Route::group(['prefix' => 'listing'], function()
	{
		Route::get('/{listing}/{slug}', 'ListingController@index')->name('listing');
		Route::get('/{listing}/{slug}/card', 'ListingController@card')->name('listing.card');
		Route::get('/{listing}/{slug}/spotlight', 'ListingController@spotlight')->middleware('auth.ajax')->name('listing.spotlight');
		Route::get('/{listing}/{slug}/verify', 'ListingController@verify')->middleware('auth.ajax')->name('listing.verify');
		Route::get('/{listing}/{slug}/star', 'ListingController@star')->middleware('auth.ajax')->name('listing.star');
		Route::get('/{listing}/{slug}/edit', 'ListingController@edit')->name('listing.edit');
		#Route::get('/{listing}/{slug}/availability', 'AvailabilityController@availability')->name('listing.availability');
		Route::any('/{id}/update', 'ListingController@update')->name('listing.update');

	});


	//ACCOUNT
	Route::group(['middleware' => ['auth', 'isVerified'], 'prefix' => 'account', 'as' => 'account.', 'namespace' => 'Account'], function()
	{
		Route::get('/', function () {
			return redirect(route('account.edit_profile.index'));
		});
		Route::resource('change_password', 'PasswordController');
		Route::resource('edit_profile', 'ProfileController');

		Route::resource('purchase-history', 'PurchaseHistoryController');
		Route::resource('favorites', 'FavoritesController');

		Route::resource('listings', 'ListingsController');
        Route::resource('orders', 'OrdersController');

        Route::get('payments/{id}/unlink', 'BankAccountController@unlink')->name('payments.unlink');
        Route::resource('bank-account', 'BankAccountController');

        Route::get('paypal/connect', 'PayPalController@connect')->name('paypal.connect');
        Route::get('paypal/callback', 'PayPalController@callback')->name('paypal.callback');

	});

	//REQUIRES AUTHENTICATION
	Route::group(['middleware' => ['auth', 'isVerified']], function () {

		//INBOX
		Route::resource('inbox', 'InboxController')->middleware('talk'); //Inbox
        Route::get('/inbox/messages/{id}', 'InboxController@messages')->name('inbox.messages');

		//CREATE LISTING
		Route::resource('create', 'CreateController');
        Route::any('/create/{listing}/session', 'CreateController@session')->name('create.session');
        Route::get('/create/{listing}/images', 'CreateController@images')->name('create.images');
        Route::get('/create/{listing}/additional', 'CreateController@additional')->name('create.additional');
        Route::get('/create/{listing}/pricing', 'CreateController@pricing')->name('create.pricing');
        Route::get('/create/{listing}/times', 'CreateController@getTimes')->name('create.times');
        Route::post('/create/{listing}/times', 'CreateController@postTimes')->name('create.times');
        Route::get('/create/{listing}/boost', 'CreateController@boost')->name('create.boost');

        Route::post('/create/{listing}/uploads', 'CreateController@upload')->name('create.upload');
        Route::delete('/create/{listing}/image/{uuid?}', 'CreateController@deleteUpload')->name('create.delete-image');

        #Route::delete('/uploads/delete/{id}', array('as' => 'upload', 'uses' => 'CreateController@deleteUpload'))->name('create.delete-image');;
		#Route::get('/listings/{id}/session', array('as' => 'create', 'uses' => 'CreateController@session'));

		//CHECKOUT
        Route::get('/checkout/error', 'CheckoutController@error_page')->name('checkout.error');
        Route::get('/checkout/{listing}', 'CheckoutController@index')->name('checkout');
        Route::post('/checkout/{listing}', 'CheckoutController@store')->name('checkout.store');
        Route::get('/checkout/{session}/callback', 'CheckoutController@callback')->name('checkout.callback');
        Route::any('/checkout/process/{listing}', 'CheckoutController@process')->name('checkout.process');
		#Route::any('/checkout/test', 'CheckoutController@test')->name('checkout.test');
		#Route::resource('stripe', 'StripeController');
		#Route::any('/stripe/connect', 'StripeController@connect')->name('stripe.connect');

        Route::any('/paypal/{listing}/start', 'PaypalController@start')->name('paypal.start');
        Route::any('/paypal/cancel', 'PaypalController@cancel')->name('paypal.cancel');
        Route::any('/paypal/callback', 'PaypalController@callback')->name('paypal.callback');
        Route::any('/paypal/confirm', 'PaypalController@confirm')->name('paypal.confirm');
        #Route::any('/paypal/create_agreement', 'PaypalController@create_agreement')->name('paypal.create_agreement');


    });

    //REQUIRES AUTHENTICATION
    Route::group(['middleware' => ['auth']], function () {

        Route::get('email-verification', 'Auth\EmailVerificationController@index')->name('email-verification.index');
        Route::get('resend-verification', 'Auth\EmailVerificationController@resend')->name('email-verification.resend');
        Route::get('email-verified', 'Auth\EmailVerificationController@verified')->name('email-verification.verified');

    });

	Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
	Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');


});

#errors
Route::get('/suspended',function(){
    return 'Sorry something went wrong.';
})->name('error.suspended');

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    //
    use \Spiritix\LadaCache\Database\LadaCacheTrait;
    protected $casts = [
        'items' => 'json',
    ];
    public $translatable = ['title', 'url'];
    public $fillable = ['locale'];
}

resources/views/panel/menu/create.blade.php
@extends('panel::layouts.master')

@section('content')
    <a href="{{ route('panel.menu.index') }}" class="mb-1"><i class="fa fa-angle-left" aria-hidden="true"></i> back</a>

    <div class="row mb-3">
        <div class="col-sm-8">
            @if(!$form->getModel())
            <h2  class="mt-xxs">Adding menu item</h2>
            @else
            <h2  class="mt-xxs">Editing menu item</h2>
            @endif
        </div>
        <div class="col-sm-4">

        </div>

    </div>

    <div class="row">

        <div class="col-sm-12">

          <div class="panel panel-default">
              <div class="panel-body">

                  {!! form_start($form)  !!}
                  {!! form_rest($form)   !!}
                  {!! form_end($form, false)   !!}
              </div>
            </div>
    </div>

        <script type="text/javascript">

            $(document).on('turbolinks:load', function() {
                tinymce.init({
                    selector: '[name=content]',
                    height: 500,
                    menubar: false,
                    plugins: [
                        'advlist autolink lists link image charmap print preview anchor textcolor',
                        'searchreplace visualblocks code fullscreen',
                        'insertdatetime media table contextmenu paste code help'
                    ],
                    toolbar: 'undo redo | bold italic | link image',
                    content_css: [
                    ]
                });
            });

            $(document).on('turbolinks:before-cache', function() {
                // Tear down TinyMCE editor instances between Turbolinks pages
                tinymce.remove();
            });
        </script>
@endsection

resources/views/panel/menu/index.blade.php
@extends('panel::layouts.master')

@section('content')
    
    <h2>Menu</h2>

    @include("panel::components.content_menu")
    @include('alert::bootstrap')
    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <div class="btn-group" role="group">
            <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{app('laravellocalization')->getSupportedLocales()[$selected_lang]['name']}}
            </button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                <a class="dropdown-item" href="?locale={{ $localeCode }}">{{ $properties['native'] }}</a>
                @endforeach
            </div>
        </div>
    </div>


    <div class="row mt-3" id="instance">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">


                    <div class="row">
                        <div class="col-sm-5 mb-0">


                            <div class="form-group  mb-0">
                                <label>Title</label>
                            </div>
                        </div>
                        <div class="col-sm-5  mb-0">


                            <div class="form-group  mb-0">
                                <label>URL</label>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <label>&nbsp;</label>
                        </div>
                    </div>
                    <div class="row" v-for="(item, index) in rows">
                        <div class="col-sm-5">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="" v-model="item.title"/>
                            </div>
                        </div>
                        <div class="col-sm-5">


                            <div class="form-group">
                                <input type="text" class="form-control" v-model="item.url"/>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <p class="form-control-static"><a href="" @click.prevent="remove(index)"><i class="mdi mdi-delete"></i></a></p>
                        </div>
                    </div>

                    <a href="" @click.prevent="addItem"><i class="mdi mdi-plus"></i> Add menu item</a>
                    <br />
                    <br />
                    <a href="" class="btn btn-primary" @click.prevent="saveMenu">Save menu</a>

                </div>
            </div>
        </div>
    </div>
    @javascript('selected_lang', $selected_lang)
    @javascript('items', $menu->items)

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/axios@0.18.0/dist/axios.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.11/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/alertify.js@1.0.12/dist/js/alertify.min.js"></script>

    <script>
        var vm = new Vue({
            el: '#instance',
            data: {
                rows: items
            },
            created: function () {
                if(this.rows.length == 0) {
                    this.addItem();
                }
            },
            methods: {
                saveMenu: function () {
                    console.log(this.rows);
                    axios
                        .post("/panel/menu", {locale: selected_lang, items: this.rows})
                        .then(function(response) {
                            console.log(response);
                            alertify.alert("Saved");
                        })
                        .catch(function(error) {
                            console.log(error);
                        });
                },
                remove: function (index) {
                    this.rows.splice(index, 1);
                },
                addItem: function () {
                    this.rows.push({
                        title: "",
                        url: "/",
                        position: this.rows.length+1
                    })
                }
            }

        });
    </script>
@stop