routes/admin.php
<?php

Route::group(['as' => 'panel.', 'prefix' => 'panel', 'middleware' => ['web', 'role:admin'], 'namespace' => '\Admin'], function()
{
    Route::get('/', 'PanelController@index');
    Route::resource('listings', 'ListingsController');
	Route::get('/listings/{listing}/duplicate', 'ListingsController@duplicate')->name('listings.duplicate');
    Route::resource('categories', 'CategoriesController');
    Route::resource('users', 'UsersController');
	Route::resource('roles', 'RolesController');
    Route::resource('pages', 'PagesController');
    Route::resource('menu', 'MenuController');
    Route::any('/settings/remove', 'SettingsController@remove')->name('settings.remove');
    Route::resource('payments', 'PaymentsController');
    Route::resource('settings', 'SettingsController');
    Route::resource('orders', 'OrdersController');
    Route::resource('home', 'HomeController');
    Route::resource('addons', 'AddonsController');
    Route::get('/addon/{id}/toggle', 'AddonsController@toggle');
    Route::resource('themes', 'ThemesController');
    Route::get('/theme/{id}/toggle', 'ThemesController@toggle');
    Route::resource('pricing-models', 'PricingModelsController');
    Route::resource('fields', 'FieldsController');

});

Route::group(['as' => 'panel.', 'prefix' => 'panel', 'middleware' => ['web', 'role:admin|moderator'], 'namespace' => '\Admin'], function()
{
    Route::get('/', 'PanelController@index');
    Route::resource('users', 'UsersController');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('/test', function () {
    return view('welcome');
});
*/



include "admin.php";
include "payments.php";

Route::get('/cp', function () {
    if(env('DEMO_PANEL')) {
        \Auth::loginUsingId(1, true);
        return redirect("/panel");
    }
});

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => 'jailBanned'], function()
{
	Auth::routes();
    Route::get('email-verification', 'Auth\EmailVerificationController@sendEmailVerification')->name('email-verification.send');
    Route::get('email-verification/error', 'Auth\EmailVerificationController@getVerificationError')->name('email-verification.error');
    Route::get('email-verification/check/{token}', 'Auth\EmailVerificationController@getVerification')->name('email-verification.check');

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/browse', 'BrowseController@listings')->name('browse');
    Route::get('/categories', 'BrowseController@categories')->name('categories');

    Route::get('/pages/{slug?}', 'PageController@index')->name('page');
	Route::get('/contact', 'ContactController@index')->name('contact');
	Route::post('/contact', 'ContactController@postIndex')->name('contact.post');

	Route::get('/profile/{user}', 'ProfileController@index')->name('profile'); //PROFILE
	Route::get('/profile/{user}/follow', 'ProfileController@follow')->name('profile.follow'); //PROFILE

	//LISTINGS
	Route::group(['prefix' => 'listing'], function()
	{
		Route::get('/{listing}/{slug}', 'ListingController@index')->name('listing');
		Route::get('/{listing}/{slug}/card', 'ListingController@card')->name('listing.card');
		Route::get('/{listing}/{slug}/spotlight', 'ListingController@spotlight')->middleware('auth.ajax')->name('listing.spotlight');
		Route::get('/{listing}/{slug}/verify', 'ListingController@verify')->middleware('auth.ajax')->name('listing.verify');
		Route::get('/{listing}/{slug}/star', 'ListingController@star')->middleware('auth.ajax')->name('listing.star');
		Route::get('/{listing}/{slug}/edit', 'ListingController@edit')->name('listing.edit');
		#Route::get('/{listing}/{slug}/availability', 'AvailabilityController@availability')->name('listing.availability');
		Route::any('/{id}/update', 'ListingController@update')->name('listing.update');

	});


	//ACCOUNT
	Route::group(['middleware' => ['auth', 'isVerified'], 'prefix' => 'account', 'as' => 'account.', 'namespace' => 'Account'], function()
	{
		Route::get('/', function () {
			return redirect(route('account.edit_profile.index'));
		});
		Route::resource('change_password', 'PasswordController');
		Route::resource('edit_profile', 'ProfileController');

		Route::resource('purchase-history', 'PurchaseHistoryController');
		Route::resource('favorites', 'FavoritesController');

		Route::resource('listings', 'ListingsController');
        Route::resource('orders', 'OrdersController');

        Route::get('payments/{id}/unlink', 'BankAccountController@unlink')->name('payments.unlink');
        Route::resource('bank-account', 'BankAccountController');

        Route::get('paypal/connect', 'PayPalController@connect')->name('paypal.connect');
        Route::get('paypal/callback', 'PayPalController@callback')->name('paypal.callback');

	});

	//REQUIRES AUTHENTICATION
	Route::group(['middleware' => ['auth', 'isVerified']], function () {

		//INBOX
		Route::resource('inbox', 'InboxController')->middleware('talk'); //Inbox
        Route::get('/inbox/messages/{id}', 'InboxController@messages')->name('inbox.messages');

		//CREATE LISTING
		Route::resource('create', 'CreateController');
        Route::any('/create/{listing}/session', 'CreateController@session')->name('create.session');
        Route::get('/create/{listing}/images', 'CreateController@images')->name('create.images');
        Route::get('/create/{listing}/additional', 'CreateController@additional')->name('create.additional');
        Route::get('/create/{listing}/pricing', 'CreateController@pricing')->name('create.pricing');
        Route::get('/create/{listing}/times', 'CreateController@getTimes')->name('create.times');
        Route::post('/create/{listing}/times', 'CreateController@postTimes')->name('create.times');
        Route::get('/create/{listing}/boost', 'CreateController@boost')->name('create.boost');

        Route::post('/create/{listing}/uploads', 'CreateController@upload')->name('create.upload');
        Route::delete('/create/{listing}/image/{uuid?}', 'CreateController@deleteUpload')->name('create.delete-image');

        #Route::delete('/uploads/delete/{id}', array('as' => 'upload', 'uses' => 'CreateController@deleteUpload'))->name('create.delete-image');;
		#Route::get('/listings/{id}/session', array('as' => 'create', 'uses' => 'CreateController@session'));

		//CHECKOUT
        Route::get('/checkout/error', 'CheckoutController@error_page')->name('checkout.error');
        Route::get('/checkout/{listing}', 'CheckoutController@index')->name('checkout');
        Route::post('/checkout/{listing}', 'CheckoutController@store')->name('checkout.store');
        Route::get('/checkout/{session}/callback', 'CheckoutController@callback')->name('checkout.callback');
        Route::any('/checkout/process/{listing}', 'CheckoutController@process')->name('checkout.process');
		#Route::any('/checkout/test', 'CheckoutController@test')->name('checkout.test');
		#Route::resource('stripe', 'StripeController');
		#Route::any('/stripe/connect', 'StripeController@connect')->name('stripe.connect');

        Route::any('/paypal/{listing}/start', 'PaypalController@start')->name('paypal.start');
        Route::any('/paypal/cancel', 'PaypalController@cancel')->name('paypal.cancel');
        Route::any('/paypal/callback', 'PaypalController@callback')->name('paypal.callback');
        Route::any('/paypal/confirm', 'PaypalController@confirm')->name('paypal.confirm');
        #Route::any('/paypal/create_agreement', 'PaypalController@create_agreement')->name('paypal.create_agreement');


    });

    //REQUIRES AUTHENTICATION
    Route::group(['middleware' => ['auth']], function () {

        Route::get('email-verification', 'Auth\EmailVerificationController@index')->name('email-verification.index');
        Route::get('resend-verification', 'Auth\EmailVerificationController@resend')->name('email-verification.resend');
        Route::get('email-verified', 'Auth\EmailVerificationController@verified')->name('email-verification.verified');

    });

	Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
	Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');


});

#errors
Route::get('/suspended',function(){
    return 'Sorry something went wrong.';
})->name('error.suspended');

app/Models/Order.php
<?php

namespace App\Models;

use App\Traits\OrderId;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Sofa\Eloquence\Eloquence; // base trait
use Sofa\Eloquence\Metable; // extension trait

class Order extends Model
{
    //
    use Eloquence, Metable;
    use SoftDeletes;

    use OrderId;
    protected $casts = [
        'token' => 'array',
        'listing_options' => 'array',
        'user_choices' => 'array',
        'customer_details' => 'array',
    ];
	protected $dates = [
        'accepted_at',
        'declined_at',
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    protected $searchableColumns = ['listing.title', 'user.email'];

    protected $searchable = [
        'columns' => [
            'listings.title' => 10,
            'users.name' => 10,
            'users.email' => 10,
        ],
        'joins' => [
            'listings' => ['orders.listing_id','listings.id'],
            'users' => ['orders.user_id','users.id'],
            //'sellers' => ['listings.user_id','listings.id'],
        ],
    ];
    protected $appends = ['hash'];

    public function getHashAttribute($value) {
        return $this->getRouteKey();
    }

    public function listing() {
      return $this->belongsTo('App\Models\Listing');
    }

    public function payment_gateway() {
      return $this->belongsTo('App\Models\PaymentGateway');
    }

    public function seller() {
      return $this->belongsTo('App\Models\User', 'seller_id');
    }
	
    public function user() {
      return $this->belongsTo('App\Models\User');
    }

}

app/Http/Controllers/Account/OrdersController.php
<?php

namespace App\Http\Controllers\Account;

use App\Mail\AcceptPurchase;
use App\Mail\DeclinePurchase;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Order;
use Carbon\Carbon;
use Mail;
use Talk;

class OrdersController extends Controller
{

    public function index()
    {


        $orders = Order::with('listing', 'user')->where('seller_id', auth()->user()->id)->orderBy('id', 'DESC')->paginate(10);
        return view('account.orders.index', compact('orders'));
    }

    public function show($order)
    {

        $this->authorize('update', $order);

        /*$user = auth()->user();
        dd($user->stripe_id);
        $user->stripe_id = 'hello world';
        $user->save();*/

        return view('account.orders.show', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $order)
    {
        //
        $this->authorize('update', $order);

        $user = auth()->user();

        if($request->input('status') == 'accept') {

            if($order->payment_gateway->name == 'stripe') {
                \Stripe\Stripe::setApiKey(config('marketplace.stripe_secret_key'));
                $charge = \Stripe\Charge::retrieve($order->authorization_id, ["stripe_account" => $order->payment_gateway->gateway_id]);
                $result = $charge->capture();
                $order->capture_id = $charge->id;
            }

            $order->accepted_at = Carbon::now();
            $order->status = 'accepted';
            $order->save();

            Mail::to($order->user->email)->send(new AcceptPurchase($order));

        }
        if($request->input('status') == 'decline') {

            if($order->payment_gateway->name == 'stripe') {
                \Stripe\Stripe::setApiKey(config('marketplace.stripe_secret_key'));
                $charge = \Stripe\Charge::retrieve($order->authorization_id, ["stripe_account" => $order->payment_gateway->gateway_id]);

                $refund = \Stripe\Refund::create(array(
                    "charge" => $charge->id
                ), ["stripe_account" 	=> $order->payment_gateway->gateway_id]);

                $order->refund_id = $refund->id;
            }

            $order->declined_at = Carbon::now();
            $order->status = 'declined';
            $order->save();

            Mail::to($order->user->email)->send(new DeclinePurchase($order));
        }

        if($request->input('notes')) {
            Talk::setAuthUserId(auth()->user()->id);
            Talk::sendMessageByUserId($order->user_id, $request->get('notes'));
            $order->user->increment('unread_messages');
        }

        $request->session()->flash('refresh_cache', 'OK');

        return redirect(route('account.orders.show', $order));
    }
}

resources/views/panel/orders/index.blade.php
@extends('panel::layouts.master')

@section('content')
    
    <h2>Orders</h2>
<br />
    @include('alert::bootstrap')
    {!! Form::open(['url' => url()->current(), 'method' => 'GET']) !!}
    <div class="input-group mb-3">
        {{Form::text('q', request('q'), ['class' => 'form-control', 'placeholder' => "Search..."])}}
        <div class="input-group-append">
            <button class="btn btn-secondary" type="submit">Search</button>
        </div>
    </div>
    {!! Form::close() !!}
    <table class="table table-sm table-striped">
        <thead class="thead- border-0">
        <tr>
            <th scope="col" class="border-0">#</th>
            <th scope="col" class="border-0">Listing</th>
            <th scope="col" class="border-0">Seller</th>
            <th scope="col" class="border-0">Buyer</th>
            <th scope="col" class="border-0">Amount</th>
            <th scope="col"  class="border-0"></th>
        </tr>
        </thead>
        <tbody>
        @foreach($orders as $item)
            <tr>
                <td>{{ $item->hash }}</td>
                <td>{{str_limit($item->listing->title, 40)}}</td>
                <td>{{$item->listing->user->email}}</td>
                <td>{{$item->user->email}}</td>
                <td>{{$item->amount}} {{$item->currency}}</td>
                <td>{{$item->created_at->toFormattedDateString()}}</td>
                <td>
                    <a href="{{route('panel.orders.show', $item)}}" class="text-muted float-right"><i class="fa fa-eye"></i></a>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>

    {{ $orders->appends(app('request')->except('page'))->links() }}

@stop

resources/views/panel/orders/show.blade.php
@extends('panel::layouts.master')

@section('content')
    <a href="{{ route('panel.orders.index') }}" class="mb-1"><i class="fa fa-angle-left" aria-hidden="true"></i> back</a>

    <div class="row mb-3">
        <div class="col-sm-8">
            <h2  class="mt-xxs">Viewing order #{{$order->hash}}</h2>
        </div>
        <div class="col-sm-4">

        </div>

    </div>

    <div class="row">

        <div class="col-sm-12">

            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th scope="row">Listing</th>
                        <td>{{$order->listing->title}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Status</th>
                        <td><span class="badge badge-warning">{{$order->status}}</span></td>
                    </tr>
                    <tr>
                        <th scope="row">Amount</th>
                        <td>{{$order->amount}} {{$order->currency}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Service fee</th>
                        <td>{{$order->service_fee}} {{$order->currency}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Buyer</th>
                        <td>{{$order->user->name}} ({{$order->user->email}})<br />
                            <pre>{!! array_to_string($order->customer_details) !!}</pre>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Seller</th>
                        <td>{{$order->listing->user->name}} ({{$order->listing->user->email}}) @if($order->payment_gateway)- <a href="https://dashboard.stripe.com/{{$order->payment_gateway->gateway_id}}/payments/{{$order->authorization_id}}" target="_blank">{{$order->payment_gateway->gateway_id}}</a>@endif</td>
                    </tr>
                    <tr>
                        <th scope="row">Date&nbsp;Placed</th>
                        <td>{{$order->created_at->toDayDateTimeString()}}</td>
                    </tr>
                </tbody>
            </table>

    </div>

@endsection