routes/admin.php
<?php

Route::group(['as' => 'panel.', 'prefix' => 'panel', 'middleware' => ['web', 'role:admin'], 'namespace' => '\Admin'], function()
{
    Route::get('/', 'PanelController@index');
    Route::resource('listings', 'ListingsController');
	Route::get('/listings/{listing}/duplicate', 'ListingsController@duplicate')->name('listings.duplicate');
    Route::resource('categories', 'CategoriesController');
    Route::resource('users', 'UsersController');
	Route::resource('roles', 'RolesController');
    Route::resource('pages', 'PagesController');
    Route::resource('menu', 'MenuController');
    Route::any('/settings/remove', 'SettingsController@remove')->name('settings.remove');
    Route::resource('payments', 'PaymentsController');
    Route::resource('settings', 'SettingsController');
    Route::resource('orders', 'OrdersController');
    Route::resource('home', 'HomeController');
    Route::resource('addons', 'AddonsController');
    Route::get('/addon/{id}/toggle', 'AddonsController@toggle');
    Route::resource('themes', 'ThemesController');
    Route::get('/theme/{id}/toggle', 'ThemesController@toggle');
    Route::resource('pricing-models', 'PricingModelsController');
    Route::resource('fields', 'FieldsController');

});

Route::group(['as' => 'panel.', 'prefix' => 'panel', 'middleware' => ['web', 'role:admin|moderator'], 'namespace' => '\Admin'], function()
{
    Route::get('/', 'PanelController@index');
    Route::resource('users', 'UsersController');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('/test', function () {
    return view('welcome');
});
*/



include "admin.php";
include "payments.php";

Route::get('/cp', function () {
    if(env('DEMO_PANEL')) {
        \Auth::loginUsingId(1, true);
        return redirect("/panel");
    }
});

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => 'jailBanned'], function()
{
	Auth::routes();
    Route::get('email-verification', 'Auth\EmailVerificationController@sendEmailVerification')->name('email-verification.send');
    Route::get('email-verification/error', 'Auth\EmailVerificationController@getVerificationError')->name('email-verification.error');
    Route::get('email-verification/check/{token}', 'Auth\EmailVerificationController@getVerification')->name('email-verification.check');

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/browse', 'BrowseController@listings')->name('browse');
    Route::get('/categories', 'BrowseController@categories')->name('categories');

    Route::get('/pages/{slug?}', 'PageController@index')->name('page');
	Route::get('/contact', 'ContactController@index')->name('contact');
	Route::post('/contact', 'ContactController@postIndex')->name('contact.post');

	Route::get('/profile/{user}', 'ProfileController@index')->name('profile'); //PROFILE
	Route::get('/profile/{user}/follow', 'ProfileController@follow')->name('profile.follow'); //PROFILE

	//LISTINGS
	Route::group(['prefix' => 'listing'], function()
	{
		Route::get('/{listing}/{slug}', 'ListingController@index')->name('listing');
		Route::get('/{listing}/{slug}/card', 'ListingController@card')->name('listing.card');
		Route::get('/{listing}/{slug}/spotlight', 'ListingController@spotlight')->middleware('auth.ajax')->name('listing.spotlight');
		Route::get('/{listing}/{slug}/verify', 'ListingController@verify')->middleware('auth.ajax')->name('listing.verify');
		Route::get('/{listing}/{slug}/star', 'ListingController@star')->middleware('auth.ajax')->name('listing.star');
		Route::get('/{listing}/{slug}/edit', 'ListingController@edit')->name('listing.edit');
		#Route::get('/{listing}/{slug}/availability', 'AvailabilityController@availability')->name('listing.availability');
		Route::any('/{id}/update', 'ListingController@update')->name('listing.update');

	});


	//ACCOUNT
	Route::group(['middleware' => ['auth', 'isVerified'], 'prefix' => 'account', 'as' => 'account.', 'namespace' => 'Account'], function()
	{
		Route::get('/', function () {
			return redirect(route('account.edit_profile.index'));
		});
		Route::resource('change_password', 'PasswordController');
		Route::resource('edit_profile', 'ProfileController');

		Route::resource('purchase-history', 'PurchaseHistoryController');
		Route::resource('favorites', 'FavoritesController');

		Route::resource('listings', 'ListingsController');
        Route::resource('orders', 'OrdersController');

        Route::get('payments/{id}/unlink', 'BankAccountController@unlink')->name('payments.unlink');
        Route::resource('bank-account', 'BankAccountController');

        Route::get('paypal/connect', 'PayPalController@connect')->name('paypal.connect');
        Route::get('paypal/callback', 'PayPalController@callback')->name('paypal.callback');

	});

	//REQUIRES AUTHENTICATION
	Route::group(['middleware' => ['auth', 'isVerified']], function () {

		//INBOX
		Route::resource('inbox', 'InboxController')->middleware('talk'); //Inbox
        Route::get('/inbox/messages/{id}', 'InboxController@messages')->name('inbox.messages');

		//CREATE LISTING
		Route::resource('create', 'CreateController');
        Route::any('/create/{listing}/session', 'CreateController@session')->name('create.session');
        Route::get('/create/{listing}/images', 'CreateController@images')->name('create.images');
        Route::get('/create/{listing}/additional', 'CreateController@additional')->name('create.additional');
        Route::get('/create/{listing}/pricing', 'CreateController@pricing')->name('create.pricing');
        Route::get('/create/{listing}/times', 'CreateController@getTimes')->name('create.times');
        Route::post('/create/{listing}/times', 'CreateController@postTimes')->name('create.times');
        Route::get('/create/{listing}/boost', 'CreateController@boost')->name('create.boost');

        Route::post('/create/{listing}/uploads', 'CreateController@upload')->name('create.upload');
        Route::delete('/create/{listing}/image/{uuid?}', 'CreateController@deleteUpload')->name('create.delete-image');

        #Route::delete('/uploads/delete/{id}', array('as' => 'upload', 'uses' => 'CreateController@deleteUpload'))->name('create.delete-image');;
		#Route::get('/listings/{id}/session', array('as' => 'create', 'uses' => 'CreateController@session'));

		//CHECKOUT
        Route::get('/checkout/error', 'CheckoutController@error_page')->name('checkout.error');
        Route::get('/checkout/{listing}', 'CheckoutController@index')->name('checkout');
        Route::post('/checkout/{listing}', 'CheckoutController@store')->name('checkout.store');
        Route::get('/checkout/{session}/callback', 'CheckoutController@callback')->name('checkout.callback');
        Route::any('/checkout/process/{listing}', 'CheckoutController@process')->name('checkout.process');
		#Route::any('/checkout/test', 'CheckoutController@test')->name('checkout.test');
		#Route::resource('stripe', 'StripeController');
		#Route::any('/stripe/connect', 'StripeController@connect')->name('stripe.connect');

        Route::any('/paypal/{listing}/start', 'PaypalController@start')->name('paypal.start');
        Route::any('/paypal/cancel', 'PaypalController@cancel')->name('paypal.cancel');
        Route::any('/paypal/callback', 'PaypalController@callback')->name('paypal.callback');
        Route::any('/paypal/confirm', 'PaypalController@confirm')->name('paypal.confirm');
        #Route::any('/paypal/create_agreement', 'PaypalController@create_agreement')->name('paypal.create_agreement');


    });

    //REQUIRES AUTHENTICATION
    Route::group(['middleware' => ['auth']], function () {

        Route::get('email-verification', 'Auth\EmailVerificationController@index')->name('email-verification.index');
        Route::get('resend-verification', 'Auth\EmailVerificationController@resend')->name('email-verification.resend');
        Route::get('email-verified', 'Auth\EmailVerificationController@verified')->name('email-verification.verified');

    });

	Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
	Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');


});

#errors
Route::get('/suspended',function(){
    return 'Sorry something went wrong.';
})->name('error.suspended');

app/Models/PricingModel.php
<?php

namespace App\Models;

#use Nicolaslopezj\Searchable\SearchableTrait;
use Illuminate\Database\Eloquent\Model;
use App\Traits\MergedBuilder;
use Grimzy\LaravelMysqlSpatial\Eloquent\SpatialTrait;
use DB;
use ChristianKuri\LaravelFavorite\Traits\Favoriteable;
use Illuminate\Database\Eloquent\SoftDeletes;
use PhpUnitsOfMeasure\PhysicalQuantity\Length;
use App\Traits\Commentable;
use App\Traits\HashId;
use Sofa\Eloquence\Eloquence;
use Spatie\SchemalessAttributes\SchemalessAttributes;

class PricingModel extends Model
{
    use \Spiritix\LadaCache\Database\LadaCacheTrait;
    protected $fillable = [
        "name", "widget", "unit_name", "duration_name"
    ];

	public $casts = [
        'meta' => 'array',
    ];
	protected $appends = ['per_label_buyer', 'per_label_buyer_display', 'quantity_label_buyer', 'quantity_label_buyer_display', 'can_seller_enter_per_label'];

    public function getPerLabelBuyerAttribute() {
        return $this->meta->per_label_buyer;
    }
	
    public function getPerLabelBuyerDisplayAttribute() {
		$name = $this->meta->per_label_buyer;
		if(!$name) {
			if($this->widget == 'book_time') {
				$name = $this->duration_name;
			}			
			if($this->widget == 'book_date') {
				$name = ($this->price_display == 'unit')?$this->unit_name:$this->duration_name;
			}
		}
        return $name;
    }
	
    public function getCanSellerEnterPerLabelAttribute() {
        return $this->meta->can_seller_enter_per_label;
    }
	
    public function getQuantityLabelBuyerAttribute() {
        return $this->meta->quantity_label_buyer;
    }
	
    public function getQuantityLabelBuyerDisplayAttribute() {
		$name = $this->meta->quantity_label_buyer;
		if(!$name) {
			if($this->widget == 'book_time') {
				$name = __('Spaces to book');
			}
		}
        return $name;
    }
	
    public function getPricingUnitAttribute() {
        if($this->price_display == 'unit') {
            return $this->unit_name;
        }
        return $this->duration_name;
    }

	public function getMetaAttribute(): SchemalessAttributes
    {
        return SchemalessAttributes::createForModel($this, 'meta');
    }

    public function scopeWithMeta(): Builder
    {
        return SchemalessAttributes::scopeWithSchemalessAttributes('meta');
    }

}

resources/views/panel/pricing-models/create.blade.php
@extends('panel::layouts.master')

@section('content')
    <div class="container">
        <a href="{{route('panel.pricing-models.index')}}" class="mb-1"><i class="fa fa-angle-left" aria-hidden="true"></i> back</a>

        <div class="row mb-3">
            <div class="col-sm-8">
                @if(!$pricing_model->exists)
                    <h2 class="mt-xxs">Adding new pricing model</h2>
                @else
                    <h2 class="mt-xxs">Editing pricing model: {{ $pricing_model->name }}</h2>
                @endif
            </div>
            <div class="col-sm-4">

            </div>

        </div>

        <div class="row">

            <div class="col-sm-8">

                <div class="panel panel-default">
                    <div class="panel-body">

                        @if(!$pricing_model->exists)
                            {!! Form::model($pricing_model, ['route' => ['panel.pricing-models.store', $pricing_model], 'method' => 'post']) !!}
                        @else
                            {!! Form::model($pricing_model, ['route' => ['panel.pricing-models.update', $pricing_model], 'method' => 'put']) !!}
                        @endif

                        <div class="form-group">
                                <label>Name</label>
                                {{ Form::text('name', null, ['class' => 'form-control']) }}
                            </div>
							
							<div class="form-group">
                                <label">Seller label</label>
                                {{ Form::text('seller_label', null, ['class' => 'form-control']) }}
								<small class="form-text text-muted">The text sellers will see when choosing a pricing method - e.g. Sell something, Rent something, List your service, Request something, List a freebie, Post an announcement</small>
                            </div>
							
                            <div class="form-group">
                                <label>Widget Type</label>
                                {{ Form::select('widget', ['buy' => 'Buy', 'book_date' => 'Book a Date', 'book_time' => 'Book a Time'], null, ['placeholder' => 'Select...', 'class' => 'form-control']) }}
                            </div>                            

                            <div class="form-group">
                                <label>Unit name</label>
                                {{ Form::text('unit_name', null, ['class' => 'form-control', 'placeholder' => 'e.g. item, unit, KG, Room, Space']) }}
                                <small class="form-text text-muted">The seller will be able to see the unit name when setting the price. e.g. a hotel owner will see price per <i>room</i>, a merchant will see price per <i>item</i>. (singular only)</small>
                            </div>

                            <div class="form-group">
                                <label>Quantity label</label>
                                {{ Form::text('quantity_label', null, ['class' => 'form-control', 'placeholder' => 'e.g. Inventory, Room, Spaces per session']) }}
                                <small class="form-text text-muted">The display name for the seller to enter a quantity for the listing. e.g. a seller listing rooms for rent would see "Rooms", a seller selling products would see "Quantity".</small>
                            </div>

                            <div class="form-group">
                                <label>Duration <small class="text-muted">(Book a date widget only)</small></label>
                                {{ Form::select('duration_name', ['day' => 'Day', 'night' => 'Night'], null, ['placeholder' => 'Select...', 'class' => 'form-control']) }}
                                <small class="form-text text-muted"></small>
                            </div>

                            <div class="form-check">
                                {{ Form::checkbox('can_add_pricing', true, null, ['class' => 'form-check-input', 'id' => 'can_add_pricing']) }}
                                <label class="form-check-label" for="can_add_pricing">Can add pricing</label>
                                <a href="" class="small text-muted" data-toggle="tooltip" data-placement="top" title="Allow sellers to add a price to their listing."><i class="fa fa-info-circle"></i></a>
                            </div>

                            <div class="form-check">
                                {{ Form::checkbox('can_accept_payments', true, null, ['class' => 'form-check-input', 'id' => 'can_accept_payments']) }}
                                <label class="form-check-label" for="can_accept_payments">Can accept payments</label>
                                <a href="" class="small text-muted" data-toggle="tooltip" data-placement="top" title="Turn this off if you only want sellers to list their item and not accept payments."><i class="fa fa-info-circle"></i></a>
                            </div>

                            <div class="form-check">
                                {{ Form::checkbox('can_add_variants', true, null, ['class' => 'form-check-input', 'id' => 'can_add_variants']) }}
                                <label class="form-check-label" for="can_add_variants">Can add variations of the item <small class="text-muted">(Buy widget only)</small></label>
                                <a href="" class="small text-muted" data-toggle="tooltip" data-placement="top" title="Let sellers add variations e.g. colors, sizes for their product"><i class="fa fa-info-circle"></i></a>
                            </div>

                            <div class="form-check">
                                {{ Form::checkbox('can_add_shipping', true, null, ['class' => 'form-check-input', 'id' => 'can_add_shipping']) }}
                                <label class="form-check-label" for="can_add_shipping">Can add shipping fee <small class="text-muted">(Buy widget only)</small></label>
                                <a href="" class="small text-muted" data-toggle="tooltip" data-placement="top" title="Let sellers add shipping fees for their product"><i class="fa fa-info-circle"></i></a>
                            </div>

                            <div class="form-check">
                                {{ Form::checkbox('can_add_additional_pricing', true, null, ['class' => 'form-check-input', 'id' => 'can_add_additional_pricing']) }}
                                <label class="form-check-label" for="can_add_additional_pricing">Can add additional services/prices</label>
                                <a href="" class="small text-muted" data-toggle="tooltip" data-placement="top" title="Let sellers add service fees or addition options with their listing"><i class="fa fa-info-circle"></i></a>
                            </div>
                            <div class="form-check">
                                {{ Form::checkbox('requires_shipping_address', true, null, ['class' => 'form-check-input', 'id' => 'requires_shipping_address']) }}
                                <label class="form-check-label" for="requires_shipping_address">Require Shipping Address</label>
                                <a href="" class="small text-muted" data-toggle="tooltip" data-placement="top" title="Ask the user to provide shipping address"><i class="fa fa-info-circle"></i></a>
                            </div>
                            <div class="form-check">
                                {{ Form::checkbox('requires_billing_address', true, null, ['class' => 'form-check-input', 'id' => 'requires_billing_address']) }}
                                <label class="form-check-label" for="requires_billing_address">Require Billing Address</label>
                                <a href="" class="small text-muted" data-toggle="tooltip" data-placement="top" title="Ask the user to provide billing address"><i class="fa fa-info-circle"></i></a>
                            </div>


                            <button type="submit" class="btn btn-primary mt-4">Submit</button>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
@endsection

resources/views/panel/pricing-models/index.blade.php
@extends('panel::layouts.master')

@section('content')
	<h2>Pricing models <a href="{{route('panel.pricing-models.create')}}" class="btn btn-link btn-xs"><i class="mdi mdi-plus"></i> Add new</a></h2>

	@include("panel::components.settings_menu")

    @include('alert::bootstrap')
                  <table class="table">
                  	<thead>
                  		<tr>
                  			<th>#</th>
                  			<th>Title</th>
                  			<th></th>
                  		</tr>
                  	</thead>
                  	<tbody>

                        @foreach($pricing_models as $i => $pricing_model )
                  		<tr>
                  			<th scope="row">{{$i+1}}</th>
                  			<td>{{$pricing_model->name}}</td>
                  			<td><a href="{{ route('panel.pricing-models.edit', $pricing_model->id) }}">edit</a></td>
                  		</tr>
                        @endforeach
                  	</tbody>
                  </table>

@stop